In [1]:
import sys
!{sys.executable} -m pip install kagglehub
!{sys.executable} -m pip install pandas

Requirement already satisfied: kagglehub in C:\Users\larin\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.0.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in C:\Users\larin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from kagglehub) (0.1.19)
Requirement already satisfied: packaging in C:\Users\larin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from kagglehub) (26.1)
Requirement already satisfied: pyyaml in C:\Users\larin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in C:\Users\larin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from kagglehub) (2.33.1)
Requirement already satisfied: tqdm in C:\Users\larin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from kagglehub) (4.67.3)
Requirement already satisfied: protobuf in C:\Users\larin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (7.34.1)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\larin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests->kagglehub) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\larin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\larin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests->kagglehub) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\larin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests->kagglehub) (2026.1.4)
Requirement already satisfied: colorama in C:\Users\larin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from tqdm->kagglehub) (0.4.6)
Collecting pandas
  Using cached pandas-3.0.2-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy>=2.3.3 (from pandas)
  Using cached numpy-2.4.4-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\larin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\larin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in C:\Users\larin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 272.1 kB/s eta 0:00:35
   -- ------------------------------------- 0.5/9.9 MB 272.1 kB/s eta 0:00:35
   -- ------------------------------------- 0.5/9.9 MB 272.1 kB/s eta 0:00:35
   -- ------------------------------------- 0.5/9.9 MB 272.1 kB/s eta 0:00:35
   --- ------------------------------------ 0.8/9.9 MB 302.3 kB/s eta 0:00:31
   --- ------------------------------------ 0.8/9.9 MB 302.3 kB/s eta 0:00:31
   ---- ----------------------------------- 1.0/9.9 MB 350.3 kB/s eta 0:00:26
   ---- ----------------------------------- 1.0/9.9 MB 350.3 kB/s eta 0:00:26
   ---- ----------------------------------- 1.0/9.9 MB 350.3 kB/s eta 0:00:26
   ----- ---------------------------------- 1.3/9.9 MB 379.5 kB/s eta 0:00:23
   ----- ---------------------------------- 1.3/9.9 MB 379.5 kB/s eta 0:00:23
   ----- ---------------------------------- 1.3/9.9 MB 379.5 kB/s eta 0:00:23
   ----- ---------------------------------- 1.3/9.9 MB 379.5 kB/s eta 0:00:23
   ------ --------------------------------- 1.6/9.9 MB 366.0 kB/s eta 0:00:23
   ------ --------------------------------- 1.6/9.9 MB 366.0 kB/s eta 0:00:23
   ------ --------------------------------- 1.6/9.9 MB 366.0 kB/s eta 0:00:23
   ------ --------------------------------- 1.6/9.9 MB 366.0 kB/s eta 0:00:23
   ------ --------------------------------- 1.6/9.9 MB 366.0 kB/s eta 0:00:23
   ------ --------------------------------- 1.6/9.9 MB 366.0 kB/s eta 0:00:23
   ------ --------------------------------- 1.6/9.9 MB 366.0 kB/s eta 0:00:23
   ------- -------------------------------- 1.8/9.9 MB 306.4 kB/s eta 0:00:27
   ------- -------------------------------- 1.8/9.9 MB 306.4 kB/s eta 0:00:27
   ------- -------------------------------- 1.8/9.9 MB 306.4 kB/s eta 0:00:27
   ------- -------------------------------- 1.8/9.9 MB 306.4 kB/s eta 0:00:27
   ------- -------------------------------- 1.8/9.9 MB 306.4 kB/s eta 0:00:27
   ------- -------------------------------- 1.8/9.9 MB 306.4 kB/s eta 0:00:27
   ------- -------------------------------- 1.8/9.9 MB 306.4 kB/s eta 0:00:27
   ------- -------------------------------- 1.8/9.9 MB 306.4 kB/s eta 0:00:27
   -------- ------------------------------- 2.1/9.9 MB 267.3 kB/s eta 0:00:30
   -------- ------------------------------- 2.1/9.9 MB 267.3 kB/s eta 0:00:30
   -------- ------------------------------- 2.1/9.9 MB 267.3 kB/s eta 0:00:30
   -------- ------------------------------- 2.1/9.9 MB 267.3 kB/s eta 0:00:30
   -------- ------------------------------- 2.1/9.9 MB 267.3 kB/s eta 0:00:30
   -------- ------------------------------- 2.1/9.9 MB 267.3 kB/s eta 0:00:30
   --------- ------------------------------ 2.4/9.9 MB 259.6 kB/s eta 0:00:29
   --------- ------------------------------ 2.4/9.9 MB 259.6 kB/s eta 0:00:29
   --------- ------------------------------ 2.4/9.9 MB 259.6 kB/s eta 0:00:29
   --------- ------------------------------ 2.4/9.9 MB 259.6 kB/s eta 0:00:29
   --------- ------------------------------ 2.4/9.9 MB 259.6 kB/s eta 0:00:29
   --------- ------------------------------ 2.4/9.9 MB 259.6 kB/s eta 0:00:29
   --------- ------------------------------ 2.4/9.9 MB 259.6 kB/s eta 0:00:29
   ---------- ----------------------------- 2.6/9.9 MB 247.8 kB/s eta 0:00:30
   ---------- ----------------------------- 2.6/9.9 MB 247.8 kB/s eta 0:00:30
   ---------- ----------------------------- 2.6/9.9 MB 247.8 kB/s eta 0:00:30
   ---------- ----------------------------- 2.6/9.9 MB 247.8 kB/s eta 0:00:30
   ---------- ----------------------------- 2.6/9.9 MB 247.8 kB/s eta 0:00:30
   ---------- ----------------------------- 2.6/9.9 MB 247.8 kB/s eta 0:00:30
   ----------- ---------------------------- 2.9/9.9 MB 242.5 kB/s eta 0:00:29
   ----------- ---------------------------- 2.9/9.9 MB 242.5 kB/s eta 0:00:29
   ----------- ---------------------------- 2.9/9.9 MB 242.5 kB/s eta 0:00:29
   ----------- ---------------------------- 2.9/9.9 MB 242.5 kB/s eta 0:00:29
   ----------- ---------------------------- 2.9/9.9 MB 242.5 kB/s eta 0:00:29
   ----------- ---------------------------- 2.9/9.9 MB 242.5 kB/s eta 0:00:29
   ----------- ---------------------------- 2.9/9.9 MB 242.5 kB/s eta 0:00:29
   ------------ --------------------------- 3.1/9.9 MB 235.9 kB/s eta 0:00:29
   ------------ --------------------------- 3.1/9.9 MB 235.9 kB/s eta 0:00:29
   ------------ --------------------------- 3.1/9.9 MB 235.9 kB/s eta 0:00:29
   ------------ --------------------------- 3.1/9.9 MB 235.9 kB/s eta 0:00:29
   ------------- -------------------------- 3.4/9.9 MB 241.4 kB/s eta 0:00:27
   ------------- -------------------------- 3.4/9.9 MB 241.4 kB/s eta 0:00:27
   ------------- -------------------------- 3.4/9.9 MB 241.4 kB/s eta 0:00:27
   ------------- -------------------------- 3.4/9.9 MB 241.4 kB/s eta 0:00:27
   -------------- ------------------------- 3.7/9.9 MB 247.2 kB/s eta 0:00:26
   -------------- ------------------------- 3.7/9.9 MB 247.2 kB/s eta 0:00:26
   -------------- ------------------------- 3.7/9.9 MB 247.2 kB/s eta 0:00:26
   -------------- ------------------------- 3.7/9.9 MB 247.2 kB/s eta 0:00:26
   --------------- ------------------------ 3.9/9.9 MB 249.7 kB/s eta 0:00:24
   --------------- ------------------------ 3.9/9.9 MB 249.7 kB/s eta 0:00:24
   --------------- ------------------------ 3.9/9.9 MB 249.7 kB/s eta 0:00:24
   --------------- ------------------------ 3.9/9.9 MB 249.7 kB/s eta 0:00:24
   --------------- ------------------------ 3.9/9.9 MB 249.7 kB/s eta 0:00:24
   --------------- ------------------------ 3.9/9.9 MB 249.7 kB/s eta 0:00:24
   ----------------- ---------------------- 4.2/9.9 MB 246.9 kB/s eta 0:00:23
   ----------------- ---------------------- 4.2/9.9 MB 246.9 kB/s eta 0:00:23
   ----------------- ---------------------- 4.2/9.9 MB 246.9 kB/s eta 0:00:23
   ----------------- ---------------------- 4.2/9.9 MB 246.9 kB/s eta 0:00:23
   ----------------- ---------------------- 4.2/9.9 MB 246.9 kB/s eta 0:00:23
   ----------------- ---------------------- 4.2/9.9 MB 246.9 kB/s eta 0:00:23
   ----------------- ---------------------- 4.2/9.9 MB 246.9 kB/s eta 0:00:23
   ----------------- ---------------------- 4.2/9.9 MB 246.9 kB/s eta 0:00:23
   ------------------ --------------------- 4.5/9.9 MB 238.0 kB/s eta 0:00:23
   ------------------ --------------------- 4.5/9.9 MB 238.0 kB/s eta 0:00:23
   ------------------ --------------------- 4.5/9.9 MB 238.0 kB/s eta 0:00:23
   ------------------ --------------------- 4.5/9.9 MB 238.0 kB/s eta 0:00:23
   ------------------ --------------------- 4.5/9.9 MB 238.0 kB/s eta 0:00:23
   ------------------ --------------------- 4.5/9.9 MB 238.0 kB/s eta 0:00:23
   ------------------- -------------------- 4.7/9.9 MB 236.2 kB/s eta 0:00:22
   ------------------- -------------------- 4.7/9.9 MB 236.2 kB/s eta 0:00:22
   ------------------- -------------------- 4.7/9.9 MB 236.2 kB/s eta 0:00:22
   ------------------- -------------------- 4.7/9.9 MB 236.2 kB/s eta 0:00:22
   ------------------- -------------------- 4.7/9.9 MB 236.2 kB/s eta 0:00:22
   ------------------- -------------------- 4.7/9.9 MB 236.2 kB/s eta 0:00:22
   ------------------- -------------------- 4.7/9.9 MB 236.2 kB/s eta 0:00:22
   ------------------- -------------------- 4.7/9.9 MB 236.2 kB/s eta 0:00:22
   -------------------- ------------------- 5.0/9.9 MB 230.2 kB/s eta 0:00:22
   -------------------- ------------------- 5.0/9.9 MB 230.2 kB/s eta 0:00:22
   -------------------- ------------------- 5.0/9.9 MB 230.2 kB/s eta 0:00:22
   -------------------- ------------------- 5.0/9.9 MB 230.2 kB/s eta 0:00:22
   -------------------- ------------------- 5.0/9.9 MB 230.2 kB/s eta 0:00:22
   -------------------- ------------------- 5.0/9.9 MB 230.2 kB/s eta 0:00:22
   -------------------- ------------------- 5.0/9.9 MB 230.2 kB/s eta 0:00:22
   --------------------- ------------------ 5.2/9.9 MB 227.1 kB/s eta 0:00:21
   --------------------- ------------------ 5.2/9.9 MB 227.1 kB/s eta 0:00:21
   --------------------- ------------------ 5.2/9.9 MB 227.1 kB/s eta 0:00:21
   --------------------- ------------------ 5.2/9.9 MB 227.1 kB/s eta 0:00:21
   --------------------- ------------------ 5.2/9.9 MB 227.1 kB/s eta 0:00:21
   --------------------- ------------------ 5.2/9.9 MB 227.1 kB/s eta 0:00:21
   --------------------- ------------------ 5.2/9.9 MB 227.1 kB/s eta 0:00:21
   --------------------- ------------------ 5.2/9.9 MB 227.1 kB/s eta 0:00:21
   --------------------- ------------------ 5.2/9.9 MB 227.1 kB/s eta 0:00:21
   --------------------- ------------------ 5.2/9.9 MB 227.1 kB/s eta 0:00:21
   --------------------- ------------------ 5.2/9.9 MB 227.1 kB/s eta 0:00:21
   --------------------- ------------------ 5.2/9.9 MB 227.1 kB/s eta 0:00:21
   ---------------------- ----------------- 5.5/9.9 MB 214.8 kB/s eta 0:00:21
   ---------------------- ----------------- 5.5/9.9 MB 214.8 kB/s eta 0:00:21
   ---------------------- ----------------- 5.5/9.9 MB 214.8 kB/s eta 0:00:21
   ---------------------- ----------------- 5.5/9.9 MB 214.8 kB/s eta 0:00:21
   ---------------------- ----------------- 5.5/9.9 MB 214.8 kB/s eta 0:00:21
   ---------------------- ----------------- 5.5/9.9 MB 214.8 kB/s eta 0:00:21
   ---------------------- ----------------- 5.5/9.9 MB 214.8 kB/s eta 0:00:21
   ---------------------- ----------------- 5.5/9.9 MB 214.8 kB/s eta 0:00:21
   ----------------------- ---------------- 5.8/9.9 MB 209.7 kB/s eta 0:00:20
   ----------------------- ---------------- 5.8/9.9 MB 209.7 kB/s eta 0:00:20
   ----------------------- ---------------- 5.8/9.9 MB 209.7 kB/s eta 0:00:20
   ----------------------- ---------------- 5.8/9.9 MB 209.7 kB/s eta 0:00:20
   ----------------------- ---------------- 5.8/9.9 MB 209.7 kB/s eta 0:00:20
   ----------------------- ---------------- 5.8/9.9 MB 209.7 kB/s eta 0:00:20
   ----------------------- ---------------- 5.8/9.9 MB 209.7 kB/s eta 0:00:20
   ------------------------ --------------- 6.0/9.9 MB 208.9 kB/s eta 0:00:19
   ------------------------ --------------- 6.0/9.9 MB 208.9 kB/s eta 0:00:19
   ------------------------ --------------- 6.0/9.9 MB 208.9 kB/s eta 0:00:19
   ------------------------ --------------- 6.0/9.9 MB 208.9 kB/s eta 0:00:19
   ------------------------- -------------- 6.3/9.9 MB 210.8 kB/s eta 0:00:17
   ------------------------- -------------- 6.3/9.9 MB 210.8 kB/s eta 0:00:17
   ------------------------- -------------- 6.3/9.9 MB 210.8 kB/s eta 0:00:17
   ------------------------- -------------- 6.3/9.9 MB 210.8 kB/s eta 0:00:17
   ------------------------- -------------- 6.3/9.9 MB 210.8 kB/s eta 0:00:17
   ------------------------- -------------- 6.3/9.9 MB 210.8 kB/s eta 0:00:17
   ------------------------- -------------- 6.3/9.9 MB 210.8 kB/s eta 0:00:17
   -------------------------- ------------- 6.6/9.9 MB 207.6 kB/s eta 0:00:16
   -------------------------- ------------- 6.6/9.9 MB 207.6 kB/s eta 0:00:16
   -------------------------- ------------- 6.6/9.9 MB 207.6 kB/s eta 0:00:16
   -------------------------- ------------- 6.6/9.9 MB 207.6 kB/s eta 0:00:16
   -------------------------- ------------- 6.6/9.9 MB 207.6 kB/s eta 0:00:16
   -------------------------- ------------- 6.6/9.9 MB 207.6 kB/s eta 0:00:16
   -------------------------- ------------- 6.6/9.9 MB 207.6 kB/s eta 0:00:16
   -------------------------- ------------- 6.6/9.9 MB 207.6 kB/s eta 0:00:16
   --------------------------- ------------ 6.8/9.9 MB 201.7 kB/s eta 0:00:16
   --------------------------- ------------ 6.8/9.9 MB 201.7 kB/s eta 0:00:16
   --------------------------- ------------ 6.8/9.9 MB 201.7 kB/s eta 0:00:16
   --------------------------- ------------ 6.8/9.9 MB 201.7 kB/s eta 0:00:16
   --------------------------- ------------ 6.8/9.9 MB 201.7 kB/s eta 0:00:16
   --------------------------- ------------ 6.8/9.9 MB 201.7 kB/s eta 0:00:16
   ---------------------------- ----------- 7.1/9.9 MB 188.1 kB/s eta 0:00:15
   ---------------------------- ----------- 7.1/9.9 MB 188.1 kB/s eta 0:00:15
   ---------------------------- ----------- 7.1/9.9 MB 188.1 kB/s eta 0:00:15
   ---------------------------- ----------- 7.1/9.9 MB 188.1 kB/s eta 0:00:15
   ---------------------------- ----------- 7.1/9.9 MB 188.1 kB/s eta 0:00:15
   ----------------------------- ---------- 7.3/9.9 MB 191.6 kB/s eta 0:00:14
   ----------------------------- ---------- 7.3/9.9 MB 191.6 kB/s eta 0:00:14
   ----------------------------- ---------- 7.3/9.9 MB 191.6 kB/s eta 0:00:14
   ----------------------------- ---------- 7.3/9.9 MB 191.6 kB/s eta 0:00:14
   ----------------------------- ---------- 7.3/9.9 MB 191.6 kB/s eta 0:00:14
   ------------------------------ --------- 7.6/9.9 MB 193.3 kB/s eta 0:00:12
   ------------------------------ --------- 7.6/9.9 MB 193.3 kB/s eta 0:00:12
   ------------------------------ --------- 7.6/9.9 MB 193.3 kB/s eta 0:00:12
   ------------------------------ --------- 7.6/9.9 MB 193.3 kB/s eta 0:00:12
   ------------------------------ --------- 7.6/9.9 MB 193.3 kB/s eta 0:00:12
   ------------------------------ --------- 7.6/9.9 MB 193.3 kB/s eta 0:00:12
   ------------------------------ --------- 7.6/9.9 MB 193.3 kB/s eta 0:00:12
   ------------------------------- -------- 7.9/9.9 MB 195.2 kB/s eta 0:00:11
   ------------------------------- -------- 7.9/9.9 MB 195.2 kB/s eta 0:00:11
   ------------------------------- -------- 7.9/9.9 MB 195.2 kB/s eta 0:00:11
   ------------------------------- -------- 7.9/9.9 MB 195.2 kB/s eta 0:00:11
   ------------------------------- -------- 7.9/9.9 MB 195.2 kB/s eta 0:00:11
   ------------------------------- -------- 7.9/9.9 MB 195.2 kB/s eta 0:00:11
   ------------------------------- -------- 7.9/9.9 MB 195.2 kB/s eta 0:00:11
   -------------------------------- ------- 8.1/9.9 MB 193.4 kB/s eta 0:00:09
   -------------------------------- ------- 8.1/9.9 MB 193.4 kB/s eta 0:00:09
   -------------------------------- ------- 8.1/9.9 MB 193.4 kB/s eta 0:00:09
   -------------------------------- ------- 8.1/9.9 MB 193.4 kB/s eta 0:00:09
   -------------------------------- ------- 8.1/9.9 MB 193.4 kB/s eta 0:00:09
   -------------------------------- ------- 8.1/9.9 MB 193.4 kB/s eta 0:00:09
   -------------------------------- ------- 8.1/9.9 MB 193.4 kB/s eta 0:00:09
   -------------------------------- ------- 8.1/9.9 MB 193.4 kB/s eta 0:00:09
   -------------------------------- ------- 8.1/9.9 MB 193.4 kB/s eta 0:00:09
   ---------------------------------- ----- 8.4/9.9 MB 190.4 kB/s eta 0:00:08
   ---------------------------------- ----- 8.4/9.9 MB 190.4 kB/s eta 0:00:08
   ---------------------------------- ----- 8.4/9.9 MB 190.4 kB/s eta 0:00:08
   ---------------------------------- ----- 8.4/9.9 MB 190.4 kB/s eta 0:00:08
   ----------------------------------- ---- 8.7/9.9 MB 194.1 kB/s eta 0:00:07
   ----------------------------------- ---- 8.7/9.9 MB 194.1 kB/s eta 0:00:07
   ----------------------------------- ---- 8.7/9.9 MB 194.1 kB/s eta 0:00:07
   ----------------------------------- ---- 8.7/9.9 MB 194.1 kB/s eta 0:00:07
   ------------------------------------ --- 8.9/9.9 MB 197.9 kB/s eta 0:00:05
   ------------------------------------ --- 8.9/9.9 MB 197.9 kB/s eta 0:00:05
   ------------------------------------ --- 8.9/9.9 MB 197.9 kB/s eta 0:00:05
   ------------------------------------ --- 8.9/9.9 MB 197.9 kB/s eta 0:00:05
   ------------------------------------- -- 9.2/9.9 MB 201.0 kB/s eta 0:00:04
   ------------------------------------- -- 9.2/9.9 MB 201.0 kB/s eta 0:00:04
   ------------------------------------- -- 9.2/9.9 MB 201.0 kB/s eta 0:00:04
   ------------------------------------- -- 9.2/9.9 MB 201.0 kB/s eta 0:00:04
   ------------------------------------- -- 9.2/9.9 MB 201.0 kB/s eta 0:00:04
   -------------------------------------- - 9.4/9.9 MB 195.8 kB/s eta 0:00:03
   -------------------------------------- - 9.4/9.9 MB 195.8 kB/s eta 0:00:03
   -------------------------------------- - 9.4/9.9 MB 195.8 kB/s eta 0:00:03
   -------------------------------------- - 9.4/9.9 MB 195.8 kB/s eta 0:00:03
   -------------------------------------- - 9.4/9.9 MB 195.8 kB/s eta 0:00:03
   ---------------------------------------  9.7/9.9 MB 194.8 kB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 194.8 kB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 194.8 kB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 195.2 kB/s  0:00:45
Downloading numpy-2.4.4-cp314-cp314-win_amd64.whl (12.4 MB)
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("nudratabbas/healthcare-fraud-detection-dataset")

print("Path to dataset files:", path)

C:\Users\larin\AppData\Local\Programs\Python\Python314\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Resuming download from 0 bytes (288208 bytes left)...
Resuming download to C:\Users\larin\.cache\kagglehub\datasets\nudratabbas\healthcare-fraud-detection-dataset\1.archive (0/288208) bytes left.

100%|████████████████████████████████████████████████████████████████████████████████| 281k/281k [00:01<00:00, 222kB/s]

Extracting files...
Path to dataset files: C:\Users\larin\.cache\kagglehub\datasets\nudratabbas\healthcare-fraud-detection-dataset\versions\1

In [27]:
import pandas as pd
import numpy as np
df = pd.read_csv(path + "/healthcare_fraud_detection.csv") 
df.head(4)

,Provider_ID,Claim_ID,Patient_Age,Patient_Gender,Diagnosis_Code,Procedure_Code,Claim_Amount,Approved_Amount,Insurance_Type,Claim_Submission_Date,Days_Between_Service_and_Claim,Number_of_Claims_Per_Provider_Monthly,Provider_Specialty,Patient_State,Claim_Status,Is_Fraud,Length_of_Stay,Visit_Type,Chronic_Condition_Flag,Prior_Visits_12m
0,P0052,C0000000,37,Male,I25.10,36415,443.51,393.16,Medicaid,2024-09-01,13,70,Cardiology,NY,Approved,0,0,Outpatient,1,2.0
1,P0121,C0000001,21,Female,E11.9,99213,467.50,461.33,Self-Pay,2022-09-05,5,62,General Practice,IL,Pending,0,5,Inpatient,1,2.0
2,P0140,C0000002,78,Female,J06.9,93000,591.69,530.06,Medicaid,2022-04-11,29,60,Cardiology,IL,Pending,0,5,Inpatient,1,3.0
3,P0202,C0000003,65,Male,I10,93000,235.15,189.11,Private,2023-10-11,22,70,General Practice,TX,Approved,0,0,Emergency,0,5.0

In [28]:
import numpy as np
(df.pivot_table(index='Provider_Specialty', columns='Claim_Status', values='Is_Fraud', aggfunc= 'mean')*100)[['Approved']].sort_values(by='Approved',ascending=False)

Claim_Status        Approved
Provider_Specialty
Orthopedics         2.638522
General Practice    2.336449
Pulmonology         2.277904
Internal Medicine   2.158774
Cardiology          2.053388
Neurology           1.383764